pub mod dining_philosophers;
pub mod gui_library;
pub mod health_stats;
pub mod library;
pub mod link_checker;
pub mod luhn_algorithm;
pub mod points_polygons;
pub mod prefix_match;
pub mod safe_ffi;
